GENERAL:
  MODE: train  #
MODEL:
  TYPE: ProjFCHead # which model/architecture
  NAME: google-perch_classification # 1 is only fc, 2 is -> 256 -> fc (NUM_PROJ_ELEMS=256)
DATA:
  DATASET: rtbc_embedded # TODO rtbc-begging-new  # dataset name
#  DATASET: rtbc-call-types # TODO rtbc-begging-new  # dataset name
  DATASET_PATH: begging # None
  CLASS: "individual"  # which label to use
  BATCH_SIZE: 32
  SCENARIO: null
#  CLASSES_TO_DROP: [ "32PC1_2021-22", "32PC1_2022-23", "STENCH_2022-23", "FOURBIRD_2021-22" ]   # any classes to drop from set
#  CLASSES_TO_DROP : ["AL_2019-20"]   # < 10 samples
#  CLASSES_TO_DROP : ["AL_2019-20", "AL_2021-22", "BUG_2021-22", "FOURBIRD_2021-22",
#                     "LES_2017-18", "LS1_2021-22", "Patience_2017-18", "W1_2020-21"]   # classes with card <50
#  CHANNEL_COUNT: 1
#  SAMPLING_RATE: 32000  # 32000 default
#  MAX_AUDIO_LENGTH: 1.0  # in s
#  USE_SILENCE_PADDING: True  # if True, will pad up to max_audio_length
#  SIGNAL_TO_NOISE_RATIO: null
#  MAX_COUNT_PER_CLS: 50
TRAIN:
  OPTIMIZER: "adamw"
  SCHEDULER: "CosineAnnealing"
  CRITERION: "CrossEntropyLoss"
  ARGS:
    BASE_LR: 0.001
    USE_X_PERC_DATA: 1.0
  EPOCHS: 200
  EARLY_STOPPER:
    PATIENCE: 3
    MIN_DELTA: 0.05
HYPERPARAMS:
  LATENT_DIM: 1280
  NUM_PROJ_ELEMS: 256
