GENERAL:
  MODE: train  #
MODEL:
  TYPE: AemNet # which model/architecture
  NAME: aemnet_classification_drop_[32PC1_2021-22--32PC1_2022-23--STENCH_2022-23--FOURBIRD_2021-22] # which specific model config
DATA:
  DATASET: rtbc-call-types  # dataset name
  DATASET_PATH: begging
  CLASS: "individual"  # which label to use
  BATCH_SIZE: 128
  SCENARIO: None
  CLASSES_TO_DROP : ["32PC1_2021-22", "32PC1_2022-23", "STENCH_2022-23", "FOURBIRD_2021-22"]   # any classes to drop from set
  CHANNEL_COUNT: 1
  SAMPLING_RATE: 32000  # 32000 default
  MAX_AUDIO_LENGTH: 2.0  # in s
  USE_SILENCE_PADDING: True  # if True, will pad up to max_audio_length
  SIGNAL_TO_NOISE_RATIO: None
TRAIN:
  OPTIMIZER: "adamw"
  SCHEDULER: "CosineAnnealing"
  CRITERION: "CrossEntropyLoss"
  ARGS:
    BASE_LR: 0.001
    USE_X_PERC_DATA: 1.0
  AUGS:
    METHODS: ["mixup", "time-masking", "gain"]
    ARGS:
      MIXUP_ALPHA: 5
      MIXUP_BETA: 2
      MIXUP_START_EPOCH: 5
      TM_MIN_BAND_PART: 0.0
      TM_MAX_BAND_PART: 0.3
      TM_FADE: False
      TM_P: 0.5
      GAIN_MIN: -6.0
      GAIN_MAX: 6.0
      GAIN_P: 0.5
  EPOCHS: 200
  EARLY_STOPPER:
    PATIENCE: 10
    MIN_DELTA: 0.01
HYPERPARAMS:
  WIDTH_MUL: 0.5
  NUM_PROJ_ELEMS: 256
  DROPOUT: 0.2