GENERAL:
  MODE: train  #
MODEL:
  TYPE: ProjFCHead # which model/architecture
  NAME: birdnet_classification-arcface_drop_[32PC1_2021-22--32PC1_2022-23--STENCH_2022-23--FOURBIRD_2021-22] # 1 is only fc, 2 is -> 256 -> fc (NUM_PROJ_ELEMS=256)
DATA:
  DATASET: rtbc_embedded # TODO rtbc-begging-new  # dataset name
  DATASET_PATH: begging # None
  CLASS: "individual"  # which label to use
  BATCH_SIZE: 128
  SCENARIO: null
#  CLASSES_TO_DROP : ["rtbc-begging-32PC1_2021-22", "rtbc-begging-32PC1_2022-23", "rtbc-begging-STENCH_2022-23", "rtbc-begging-FOURBIRD_2021-22"]   # any classes to drop from set
  CLASSES_TO_DROP : ["32PC1_2021-22", "32PC1_2022-23", "STENCH_2022-23", "FOURBIRD_2021-22"]   # any classes to drop from set
#  CLASSES_TO_DROP : ["AL_2019-20", "W1_2020-21", "LES_2017-18", "AL_2021-22", "LS1_2021-22", "BUG_2021-22", "Patience_2017-18", "FOURBIRD_2021-22", "32PC1_2021-22"]   # any classes to drop from set
TRAIN:
  OPTIMIZER: "adamw"
  SCHEDULER: "CosineAnnealing"
  CRITERION: "ArcFaceLoss"
  ARGS:
    BASE_LR: 0.001
    USE_X_PERC_DATA: 1.0
  EPOCHS: 200
  EARLY_STOPPER:
    PATIENCE: 10
    MIN_DELTA: 0.05
HYPERPARAMS:
  LATENT_DIM: 1024
  NUM_PROJ_ELEMS: 256
