GENERAL:
  MODE: train  #
MODEL:
  TYPE: ProjFCHead # which model/architecture
  NAME: birdnet_classification # 1 is only fc, 2 is -> 256 -> fc (NUM_PROJ_ELEMS=256)
DATA:
  DATASET: littleowl-fg # TODO rtbc-begging-new  # dataset name
  DATASET_PATH: birdnet-embeddings # None
  BATCH_SIZE: 32
  USE_BALANCED_DATASET: True
TRAIN:
  OPTIMIZER: "adamw"
  SCHEDULER: "CosineAnnealing"
  CRITERION: "CrossEntropyLoss"
  ARGS:
    BASE_LR: 0.001
    USE_X_PERC_DATA: 1.0
  EPOCHS: 200
  EARLY_STOPPER:
    PATIENCE: 10
    MIN_DELTA: 0.05
HYPERPARAMS:
  LATENT_DIM: 1024
  NUM_PROJ_ELEMS: 256