GENERAL:
  MODE: train  #
MODEL:
  TYPE: ProjFCHead # which model/architecture
  NAME: google-perch_classification-with-negs_drop_[PC1111--PC1110--PC1112--PC1104] # 1 is only fc, 2 is -> 256 -> fc (NUM_PROJ_ELEMS=256)
DATA:
  DATASET: chiffchaff-fg # TODO rtbc-begging-new  # dataset name
  DATASET_PATH: google-perch-embeddings # None
  BATCH_SIZE: 128
  USE_BALANCED_DATASET: True
  CLASSES_TO_DROP: ["PC1111", "PC1110", "PC1112", "PC1104"]   # any classes to drop from set
TRAIN:
  OPTIMIZER: "adamw"
  SCHEDULER: "CosineAnnealing"
  CRITERION: "EntropicOpensetLoss"
  ARGS:
    BASE_LR: 0.001
    USE_X_PERC_DATA: 1.0
  EPOCHS: 200
  EARLY_STOPPER:
    PATIENCE: 10
    MIN_DELTA: 0.05
HYPERPARAMS:
  LATENT_DIM: 1280
  NUM_PROJ_ELEMS: 256